clean_failed_entries:
  name: Clean Failed Entries
  description: Remove failed AB BLE Gateway entries from configuration
  fields:
    dry_run:
      name: Dry Run
      description: Perform a dry run without making changes
      required: false
      default: false
      selector:
        boolean: {}

reconnect:
  name: Reconnect Gateway
  description: Safely reconnect the AB BLE Gateway without restarting Home Assistant
  fields:
    entity_id:
      name: Entity ID
      description: The ID of the specific gateway to reconnect. Leave empty to reconnect all gateways.
      required: false
      selector:
        entity:
          domain: sensor
          integration: ab_ble_gateway